services:
  bitcoind:
    image:
      lightninglabs/bitcoin-core:29-alpine
    command: [
      "bitcoind",
      "-signet",
      "-printtoconsole",
      "-rpcbind=0.0.0.0",
      "-rpcallowip=0.0.0.0/0",
      "-rpcport=18443",
      "-fallbackfee=0.00001",
      "-server",
      "-txindex",
      "-blockfilterindex",
      "-coinstatsindex",
      "-rpcuser=${BITCOIN_RPCUSER}",
      "-rpcpassword=${BITCOIN_RPCPASSWORD}"
      ]
    env_file:
      - .env
    volumes:
      - bitcoind:/home/bitcoin/.bitcoin

    ports:
      - "18443:18443"
    healthcheck:
      test: [
        "CMD-SHELL",
        "bitcoin-cli -signet -rpcuser=${BITCOIN_RPCUSER} -rpcpassword=${BITCOIN_RPCPASSWORD} -rpcconnect=127.0.0.1 -rpcport=18443 getblockchaininfo || exit 1"
      ]
      interval: 5s
      timeout: 3s
      retries: 10
  cln:
    build:
      dockerfile: cln.Dockerfile
    restart: on-failure
    entrypoint: ["/root/cln/start.sh"]
    env_file:
      - .env
    volumes:
      - bitcoind:/root/.bitcoin
      - cln:/root/.lightning
    ports:
      - "9988:9988"
      - "9736:9736"
    depends_on:
      bitcoind:
        condition: service_healthy
  aspd:
    image:
      docker.io/secondark/aspd:latest
    volumes:
      - aspd:/data/aspd
      - postgres:/var/lib/postgresql/data
      - cln:/data/cln
    ports:
      - "3535:3535"
    depends_on:
      bitcoind:
        condition: service_healthy
      cln:
        condition: service_started
  bark:
    image:
      docker.io/secondark/bark:latest
    volumes:
      - bark:/root
    depends_on:
      aspd:
        condition: service_started

volumes:
  aspd:
  bark:
  cln:
  bitcoind:
  postgres:
