services:
  aspd:
    image:
      niteshbalusu/noah-aspd:latest
    volumes:
      - /home/noderunner/signet/aspd:/data/captaind
      - /home/noderunner/signet/cln:/data/cln
    ports:
      - "3535:3535"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
