services:
  bitcoin-signet:
    image:
      lightninglabs/bitcoin-core:29-alpine
    command: [
      "bitcoind",
      "-signet",
      "-printtoconsole",
      "-rpcbind=0.0.0.0",
      "-rpcallowip=0.0.0.0/0",
      "-rpcport=18443",
      "-fallbackfee=0.00001",
      "-server",
      "-txindex",
      "-blockfilterindex",
      "-coinstatsindex",
      "-rpcuser=${RPC_USER}",
      "-rpcpassword=${RPC_PASSWORD}"
      ]
    volumes:
      - /home/noderunner/signet/bitcoin:/home/bitcoin/.bitcoin

    ports:
      - "18443:18443"
    healthcheck:
      test: [
        "CMD-SHELL",
        "bitcoin-cli -signet -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD} -rpcconnect=127.0.0.1 -rpcport=18443 getblockchaininfo || exit 1"
      ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true